# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: COMP 150DL
subtitle: Deep Learning for Computer Vision
email: gen@cs.tufts.edu
organization: Tufts Computer Science
description: > # this means to ignore newlines until "baseurl:"
  Spring 2017
logo: img/tufts-logo-blue.png
logourl: cs.tufts.edu

# Build settings
markdown: kramdown
url: "https://comp150dl.github.io"
baseurl: ""
sass:
  sass_dir: _sass
include: ['_pages']

github_username:  comp150dl

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  # - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
